Ejercicio/Models/ErrorViewModel.cs
namespace Ejercicio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ejercicio/Controllers/CommentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.Model;
using Services.Services;

namespace Ejercicio.Controllers
{
    public class CommentController : Controller
    {
        private readonly InterfaceServiceComments _context;

        public CommentController(InterfaceServiceComments _context) { 
            this._context = _context;
        }

        // GET: CommentController
        public async Task<ActionResult> Index(int idPost, string message)
        {
            ViewBag.Message=message;
            List<Comment> list = await _context.GetListComments();
            if (idPost>0) {
                list = list.Where(x=>x.PostId==idPost).ToList();
            }
            return View(list);
        }

        [HttpPost]
        // GET: CommentController
        public ActionResult Index(int idPost)
        {
            try
            {
                if (idPost < 0)
                {
                    throw new Exception("Solo se permiten las identificaciones de la tabla(columna idPost)");
                }
                return RedirectToAction(nameof(Index), new { idPost = idPost });
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index), new { message = ex });
            }
        }

    }
}

Ejercicio/Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.Model;
using Services.Services;

namespace Ejercicio.Controllers
{
    public class PostController : Controller
    {
        private readonly InterfaceServicePosts _contextUser;


        public PostController(InterfaceServicePosts _contextUse)
        {
            _contextUser = _contextUse;
        }

        // GET: PostController
        [HttpGet]
        public async Task<ActionResult> Index(string text, string message)
        {
            ViewBag.Message = message;

            List<Post> lista = await _contextUser.GetListPosts();
            if (text !=null)
            {
                List<Post> listaAux = lista.Where(x => x.Title.Contains(text) || x.Body.Contains(text)).ToList();
                return View(listaAux);
            }
            return View(lista);
        }
        // POST: PostController
        [HttpPost]
        public ActionResult Index(string text)
        {
            try
            {
                if (text ==null)
                {
                    throw new Exception("Debe ingresar texto");
                }
                return RedirectToAction(nameof(Index), new { text = text});


            }
            catch (Exception ex) {
                return RedirectToAction(nameof(Index), new { message=ex.Message});
            }
        }

        [HttpPost]
        public ActionResult Recargar()
        {
            return RedirectToAction(nameof(Index), new { message ="Ingrese texto a Filtrar" });
        }
    }
}

Ejercicio/Controllers/UserController.cs
using Ejercicio.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Models.Model;
using Services.Services;

namespace Ejercicio.Controllers
{
    public class UserController : Controller
    {
        private readonly InterfaceServicesUser _contextUser;


        public UserController(InterfaceServicesUser _contextUse)
        {
            _contextUser = _contextUse;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetUsers()
        {
            List<User>list= await _contextUser.GetListUser();
            return View(list);
        }

        public async Task<IActionResult> DetailsAddress(int id)
        {
            User user = await _contextUser.GetUser(id);
            Address address = user.Address;
            Geo geo = address.Geo;
            ViewBag.Geo = geo;
            return View(address);
        }

        public async Task<IActionResult> DetailsCompany(int id)
        {
            User user = await _contextUser.GetUser(id);
            Company company = user.Company;
            return View(company);
        }

    }
}

Ejercicio/Views/Comment/Index.cshtml
@model IEnumerable<Models.Model.Comment>

   <style type="text/css"> 
   .transformacion { text-transform: capitalize;}   
   </style> 

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Comentarios</h1>
<hr/>
<div>
    <form asp-controller="Comment" asp-action="Index">
        <div>
            <input type="number" size="15" maxlength="30" name="IdPost" placeholder="IdPost">
        </div>
        <br/>
        <div class="form-group">
            <input type="submit" value="Filtrar" class="btn btn-primary" />
        </div>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PostId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PostId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <p class="transformacion">@Html.DisplayFor(modelItem => item.Body)</p>
            </td>
        </tr>
}
    </tbody>
</table>

Ejercicio/Views/Post/Index.cshtml
@model IEnumerable<Models.Model.Post>

@{
    ViewData["Title"] = "Index";
}

<h1>Posts Existentes</h1>
<hr/>
<div>
    <form asp-controller="Post" asp-action="Index">
        <label>Utilice palabras completas para obtener mejores resultados</label>
        <div>
            <input type="text" size="15" maxlength="30" name="text" placeholder="texto a filtrar">
        </div>
        <br/>
        <div class="form-group">
            <input type="submit" value="Filtrar" class="btn btn-primary" />
        </div>
    </form>
</div>
</br>
<div>
    <form asp-controller="Post" asp-action="Recargar">
        <div class="form-group">
            <input type="submit" value="Lista Completa" class="btn btn-primary" />
        </div>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
}
</div>

Ejercicio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ejercicio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ejercicio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" > 
            <div class="container-fluid" >
@*                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ejercicio</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Menu Principal &nbsp;</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetUsers">Información de Usuarios &nbsp;</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comment" asp-action="Index">&nbsp;Comentarios &nbsp;</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">&nbsp;Información de Posts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ejercicio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ejercicio/Views/User/DetailsAddress.cshtml
@model Models.Model.Address

@{
    ViewData["Title"] = "Details";
    Models.Model.Geo geo=ViewBag.Geo;
}

<h1>Details Address</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Suite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Suite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
    </dl>
</div>

<div>
    <h3>Details of Geo</h3>
    <hr />
    <dl>
        <dd class = "col-sm-2">
            @Html.DisplayName("Lat:  ")@geo.Lat
        </dd>
        <dd class = "col-sm-10">
            @Html.DisplayName("Lng:  ")@geo.lng
        </dd>
    </dl>

</div>


<div>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    <a asp-action="GetUsers" asp-controller="User">Back to List</a>
</div>

Ejercicio/Views/User/DetailsCompany.cshtml
@model Models.Model.Company

@{
    ViewData["Title"] = "DetailsCompany";
}

<h1>Company Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bs)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="GetUsers" asp-controller="User">Back to List</a>
</div>

Ejercicio/Views/User/GetUsers.cshtml
@model IEnumerable<Models.Model.User>

@{
    ViewData["Title"] = "GetUsers";
}

<h1>Lista de Usuarios</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Website)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.ActionLink("Address Details", "DetailsAddress", new {  id=item.Id }) 
            </td>
            <td>
                @Html.ActionLink("Company Details", "DetailsCompany", new {  id=item.Id }) 
            </td>
        </tr>
}
    </tbody>
</table>

Ejercicio/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos a mi página</h1>
</div>
 <hr />
<br/>
<br/>
<div  size="5" width="50%" align="center">
    <p>Use las opciones de la barra superior para seleccionar la opción a realizar</p>
</div>